-- Migration SQL pour Arduino + Fournisseurs CUIREA
-- Date: 2026-05-01

-- 1. Ajouter colonnes quantité dans FOURNISSEURS
ALTER TABLE FOURNISSEURS ADD (
    QUANTITE_COMMANDEE NUMBER(10,2) DEFAULT 0,
    QUANTITE_MESUREE NUMBER(10,2) DEFAULT 0
);

COMMENT ON COLUMN FOURNISSEURS.QUANTITE_COMMANDEE IS 'Quantité commandée en kg';
COMMENT ON COLUMN FOURNISSEURS.QUANTITE_MESUREE IS 'Quantité mesurée par balance Arduino en kg';

-- 2. Créer table pour historique des lectures de température Arduino
CREATE TABLE ARDUINO_TEMP_READINGS (
    ID_LECTURE NUMBER PRIMARY KEY,
    ID_MATIERE NUMBER DEFAULT 3 NOT NULL,
    TEMP_MATIERE NUMBER(5,2) NOT NULL,
    TEMP_AMBIANTE NUMBER(5,2) NOT NULL,
    TIMESTAMP DATE DEFAULT SYSDATE,
    IS_ALERT NUMBER(1) DEFAULT 0 CHECK (IS_ALERT IN (0,1)),
    CONSTRAINT FK_TEMP_MATIERE FOREIGN KEY (ID_MATIERE) REFERENCES MATIERES(ID_MATIERE)
);

CREATE SEQUENCE SEQ_TEMP_READINGS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_TEMP_READINGS_ID
BEFORE INSERT ON ARDUINO_TEMP_READINGS
FOR EACH ROW
BEGIN
    IF :NEW.ID_LECTURE IS NULL THEN
        SELECT SEQ_TEMP_READINGS.NEXTVAL INTO :NEW.ID_LECTURE FROM DUAL;
    END IF;
END;
/

COMMENT ON TABLE ARDUINO_TEMP_READINGS IS 'Historique des lectures de température Arduino (2x DHT11)';
COMMENT ON COLUMN ARDUINO_TEMP_READINGS.TEMP_MATIERE IS 'Température matière première (°C)';
COMMENT ON COLUMN ARDUINO_TEMP_READINGS.TEMP_AMBIANTE IS 'Température ambiante (°C)';
COMMENT ON COLUMN ARDUINO_TEMP_READINGS.IS_ALERT IS '1 si T_matière > T_ambiante (alerte), 0 sinon';

-- 3. Créer table pour historique des validations de livraison
CREATE TABLE ARDUINO_DELIVERIES (
    ID_DELIVERY NUMBER PRIMARY KEY,
    ID_FOURNISSEUR NUMBER NOT NULL,
    ID_MATIERE NUMBER NOT NULL,
    ORDERED_QTY NUMBER(10,2) NOT NULL,
    MEASURED_WEIGHT NUMBER(10,2) NOT NULL,
    VALIDATED NUMBER(1) CHECK (VALIDATED IN (0,1)),
    OPERATOR_NOTE VARCHAR2(500),
    TIMESTAMP DATE DEFAULT SYSDATE,
    CONSTRAINT FK_DELIVERY_FOURNISSEUR FOREIGN KEY (ID_FOURNISSEUR) REFERENCES FOURNISSEURS(ID_FOURNISSEUR)
);

CREATE SEQUENCE SEQ_DELIVERIES START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_DELIVERIES_ID
BEFORE INSERT ON ARDUINO_DELIVERIES
FOR EACH ROW
BEGIN
    IF :NEW.ID_DELIVERY IS NULL THEN
        SELECT SEQ_DELIVERIES.NEXTVAL INTO :NEW.ID_DELIVERY FROM DUAL;
    END IF;
END;
/

COMMENT ON TABLE ARDUINO_DELIVERIES IS 'Historique des validations de livraison par balance Arduino (HX711)';
COMMENT ON COLUMN ARDUINO_DELIVERIES.VALIDATED IS '1 si validé (écart ≤5%), 0 si rejeté';

-- 4. Mettre à jour les données existantes
UPDATE FOURNISSEURS SET QUANTITE_COMMANDEE = 0, QUANTITE_MESUREE = 0 WHERE QUANTITE_COMMANDEE IS NULL;

COMMIT;

-- Vérification
SELECT 'Migration terminée - ' || COUNT(*) || ' fournisseurs mis à jour' FROM FOURNISSEURS;
SELECT 'Table ARDUINO_TEMP_READINGS créée' FROM DUAL;
SELECT 'Table ARDUINO_DELIVERIES créée' FROM DUAL;
