-- Script pour vérifier les données des fournisseurs avec les livraisons
-- Date: 2026-05-02

-- Afficher toutes les colonnes de la table FOURNISSEURS
SELECT 
    ID_FOURNISSEUR,
    NOM_ENTREPRISE,
    EMAIL,
    TELEPHONE,
    TYPE_PRODUIT,
    STATUT,
    QTE_COMMANDEE,
    QTE_MESUREE,
    DATE_DERNIERE_LIVRAISON,
    CASE 
        WHEN QTE_COMMANDEE > 0 AND QTE_MESUREE > 0 THEN
            ROUND(ABS(QTE_MESUREE - QTE_COMMANDEE) / QTE_COMMANDEE * 100, 2)
        ELSE 0
    END AS ECART_POURCENTAGE,
    CASE 
        WHEN QTE_COMMANDEE > 0 AND QTE_MESUREE > 0 THEN
            CASE 
                WHEN ABS(QTE_MESUREE - QTE_COMMANDEE) / QTE_COMMANDEE * 100 <= 5 THEN 'CONFORME'
                ELSE 'NON CONFORME'
            END
        ELSE 'PAS DE LIVRAISON'
    END AS STATUT_LIVRAISON
FROM FOURNISSEURS
ORDER BY DATE_DERNIERE_LIVRAISON DESC NULLS LAST, NOM_ENTREPRISE;

-- Statistiques des livraisons
SELECT 
    COUNT(*) AS TOTAL_FOURNISSEURS,
    COUNT(CASE WHEN QTE_COMMANDEE > 0 THEN 1 END) AS AVEC_LIVRAISON,
    COUNT(CASE WHEN QTE_COMMANDEE > 0 AND ABS(QTE_MESUREE - QTE_COMMANDEE) / QTE_COMMANDEE * 100 <= 5 THEN 1 END) AS LIVRAISONS_CONFORMES,
    COUNT(CASE WHEN QTE_COMMANDEE > 0 AND ABS(QTE_MESUREE - QTE_COMMANDEE) / QTE_COMMANDEE * 100 > 5 THEN 1 END) AS LIVRAISONS_NON_CONFORMES,
    ROUND(AVG(CASE WHEN QTE_COMMANDEE > 0 THEN QTE_COMMANDEE END), 2) AS QTE_MOYENNE_COMMANDEE,
    ROUND(AVG(CASE WHEN QTE_MESUREE > 0 THEN QTE_MESUREE END), 2) AS QTE_MOYENNE_MESUREE
FROM FOURNISSEURS;

-- Dernières livraisons (top 10)
SELECT 
    NOM_ENTREPRISE,
    QTE_COMMANDEE || ' kg' AS COMMANDEE,
    QTE_MESUREE || ' kg' AS MESUREE,
    ROUND(ABS(QTE_MESUREE - QTE_COMMANDEE) / QTE_COMMANDEE * 100, 2) || '%' AS ECART,
    TO_CHAR(DATE_DERNIERE_LIVRAISON, 'DD/MM/YYYY HH24:MI:SS') AS DATE_LIVRAISON,
    CASE 
        WHEN ABS(QTE_MESUREE - QTE_COMMANDEE) / QTE_COMMANDEE * 100 <= 5 THEN '✓ CONFORME'
        ELSE '✗ NON CONFORME'
    END AS STATUT
FROM FOURNISSEURS
WHERE QTE_COMMANDEE > 0
ORDER BY DATE_DERNIERE_LIVRAISON DESC
FETCH FIRST 10 ROWS ONLY;
