-- Créer la table EMPLOYE
CREATE TABLE EMPLOYE (
    ID_EMPLOYE NUMBER PRIMARY KEY,
    MATRICULE VARCHAR2(20) NOT NULL UNIQUE,
    NOM VARCHAR2(50) NOT NULL,
    PRENOM VARCHAR2(50) NOT NULL,
    CIN VARCHAR2(20) NOT NULL UNIQUE,
    DATE_NAISSANCE DATE NOT NULL,
    SEXE VARCHAR2(10) NOT NULL,
    ADRESSE VARCHAR2(200),
    TELEPHONE VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    POSTE VARCHAR2(50) NOT NULL,
    SPECIALITE VARCHAR2(100),
    DEPARTEMENT VARCHAR2(50) NOT NULL,
    DATE_EMBAUCHE DATE NOT NULL,
    DATE_CREATION DATE DEFAULT SYSDATE,
    STATUT VARCHAR2(20) DEFAULT 'ACTIF'
);

-- Créer la séquence pour l'auto-incrémentation
CREATE SEQUENCE SEQ_EMPLOYE
START WITH 1
INCREMENT BY 1;

-- Créer le trigger pour auto-incrémenter l'ID
CREATE OR REPLACE TRIGGER TRG_EMPLOYE_AI
    BEFORE INSERT ON EMPLOYE
    FOR EACH ROW
BEGIN
    IF :NEW.ID_EMPLOYE IS NULL THEN
        SELECT SEQ_EMPLOYE.NEXTVAL INTO :NEW.ID_EMPLOYE FROM DUAL;
    END IF;
END;
/

-- Ajouter quelques données de test
INSERT INTO EMPLOYE (MATRICULE, NOM, PRENOM, CIN, DATE_NAISSANCE, SEXE,
                      TELEPHONE, EMAIL, POSTE, DEPARTEMENT, DATE_EMBAUCHE)
VALUES ('EMP-001', 'Benali', 'Ahmed', 'AB123', TO_DATE('15/03/1985', 'DD/MM/YYYY'), 'Homme',
        '0612345678', 'ahmed.benali@email.com', 'Supervisor', 'Production', SYSDATE);

INSERT INTO EMPLOYE (MATRICULE, NOM, PRENOM, CIN, DATE_NAISSANCE, SEXE,
                      TELEPHONE, EMAIL, POSTE, DEPARTEMENT, DATE_EMBAUCHE)
VALUES ('EMP-002', 'Zahra', 'Fatima', 'CD234', TO_DATE('22/07/1990', 'DD/MM/YYYY'), 'Femme',
        '0623456789', 'fatima.zahra@email.com', 'Inspector', 'Quality Control', SYSDATE);

INSERT INTO EMPLOYE (MATRICULE, NOM, PRENOM, CIN, DATE_NAISSANCE, SEXE,
                      TELEPHONE, EMAIL, POSTE, DEPARTEMENT, DATE_EMBAUCHE)
VALUES ('EMP-003', 'Alami', 'Mohammed', 'EF345', TO_DATE('10/11/1988', 'DD/MM/YYYY'), 'Homme',
        '0634567890', 'mohammed.alami@email.com', 'Operator', 'Cutting', SYSDATE);

COMMIT;

-- Vérifier les données insérées
SELECT * FROM EMPLOYE;
