-- ================================================================
-- BASE DE DONNÉES DE RÉFÉRENCE - USINE MARROQUINERIE "LEATHER PRO"
-- Structure identique à la table Articles
-- ================================================================

DROP TABLE REF_ARTICLES_MARCHE CASCADE CONSTRAINTS;
DROP SEQUENCE seq_ref_articles;

CREATE TABLE REF_ARTICLES_MARCHE (
    id_article         NUMBER PRIMARY KEY,
    reference          VARCHAR2(50) UNIQUE NOT NULL,
    nom                VARCHAR2(100),
    categorie          VARCHAR2(100),
    type               VARCHAR2(50),
    couleur            VARCHAR2(50),
    dimension          VARCHAR2(50),
    prix_unitaire      NUMBER(10,2),
    cout_fabrication   NUMBER(10,2),
    statut             VARCHAR2(50),
    date_creation      DATE
);

CREATE SEQUENCE seq_ref_articles START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_ref_articles_id
BEFORE INSERT ON REF_ARTICLES_MARCHE
FOR EACH ROW
BEGIN
    IF :NEW.ID_ARTICLE IS NULL THEN
        SELECT seq_ref_articles.NEXTVAL INTO :NEW.ID_ARTICLE FROM DUAL;
    END IF;
END;
/

-- ================================================================
-- 50 ARTICLES DE RÉFÉRENCE - Marché maroquinerie Tunisie/Maghreb
-- ================================================================

-- SACS (15 articles)
INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-SAC-001','Sac à Main Classique','Sacs','Sac à main','Noir','30x25x10cm',120.00,45.00,'disponible',TO_DATE('2023-01-10','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-SAC-002','Sac à Main Élégant','Sacs','Sac à main','Marron','28x22x8cm',110.00,42.00,'disponible',TO_DATE('2023-01-15','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-SAC-003','Sac à Main Luxe','Sacs','Sac à main','Camel','32x26x12cm',160.00,55.00,'disponible',TO_DATE('2023-02-01','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-SAC-004','Sac à Main Standard','Sacs','Sac à main','Beige','25x20x8cm',89.00,35.00,'disponible',TO_DATE('2023-02-10','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-SAC-005','Sac à Main Rouge','Sacs','Sac à main','Rouge','30x24x10cm',125.00,48.00,'disponible',TO_DATE('2023-02-20','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-SAC-006','Sac Bandoulière Noir','Sacs','Sac bandoulière','Noir','28x20x8cm',95.00,38.00,'disponible',TO_DATE('2023-03-01','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-SAC-007','Sac Bandoulière Marron','Sacs','Sac bandoulière','Marron','26x18x7cm',88.00,35.00,'disponible',TO_DATE('2023-03-10','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-SAC-008','Sac Bandoulière Premium','Sacs','Sac bandoulière','Camel','30x22x9cm',115.00,44.00,'disponible',TO_DATE('2023-03-20','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-SAC-009','Sac Bandoulière Marine','Sacs','Sac bandoulière','Bleu Marine','28x20x8cm',99.00,40.00,'disponible',TO_DATE('2023-04-01','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-SAC-010','Tote Bag Noir','Sacs','Tote bag','Noir','40x35x15cm',75.00,30.00,'disponible',TO_DATE('2023-04-10','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-SAC-011','Tote Bag Camel','Sacs','Tote bag','Camel','42x36x15cm',80.00,32.00,'disponible',TO_DATE('2023-04-20','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-SAC-012','Tote Bag Premium','Sacs','Tote bag','Marron','40x35x15cm',85.00,34.00,'disponible',TO_DATE('2023-05-01','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-SAC-013','Sac à Dos Noir','Sacs','Sac à dos','Noir','35x28x12cm',145.00,55.00,'disponible',TO_DATE('2023-05-10','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-SAC-014','Sac à Dos Marron','Sacs','Sac à dos','Marron','33x26x11cm',138.00,52.00,'disponible',TO_DATE('2023-05-20','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-SAC-015','Sac à Dos Luxe','Sacs','Sac à dos','Camel','35x28x12cm',160.00,60.00,'disponible',TO_DATE('2023-06-01','YYYY-MM-DD'));

-- PORTEFEUILLES (10 articles)
INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-POR-001','Portefeuille Long Noir','Portefeuilles','Portefeuille long','Noir','19x10x2cm',55.00,18.00,'disponible',TO_DATE('2023-01-05','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-POR-002','Portefeuille Long Marron','Portefeuilles','Portefeuille long','Marron','19x10x2cm',62.00,20.00,'disponible',TO_DATE('2023-01-20','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-POR-003','Portefeuille Long Camel','Portefeuilles','Portefeuille long','Camel','20x10x2cm',68.00,22.00,'disponible',TO_DATE('2023-02-05','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-POR-004','Portefeuille Long Luxe','Portefeuilles','Portefeuille long','Noir','19x10x2cm',85.00,28.00,'disponible',TO_DATE('2023-02-15','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-POR-005','Portefeuille Compact Noir','Portefeuilles','Portefeuille compact','Noir','12x9x2cm',42.00,14.00,'disponible',TO_DATE('2023-03-05','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-POR-006','Portefeuille Compact Marron','Portefeuilles','Portefeuille compact','Marron','12x9x2cm',45.00,15.00,'disponible',TO_DATE('2023-03-15','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-POR-007','Portefeuille Compact Premium','Portefeuilles','Portefeuille compact','Camel','12x9x2cm',55.00,18.00,'disponible',TO_DATE('2023-04-05','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-POR-008','Porte-Cartes Noir','Portefeuilles','Porte-cartes','Noir','11x7x1cm',25.00,8.00,'disponible',TO_DATE('2023-04-15','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-POR-009','Porte-Cartes Marron','Portefeuilles','Porte-cartes','Marron','11x7x1cm',28.00,9.00,'disponible',TO_DATE('2023-05-05','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-POR-010','Porte-Cartes Premium','Portefeuilles','Porte-cartes','Camel','11x7x1cm',38.00,12.00,'disponible',TO_DATE('2023-05-15','YYYY-MM-DD'));

-- CEINTURES (12 articles)
INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-CEI-001','Ceinture Classique Noir','Ceintures','Ceinture classique','Noir','110x3.5cm',45.00,15.00,'disponible',TO_DATE('2023-01-08','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-CEI-002','Ceinture Classique Marron','Ceintures','Ceinture classique','Marron','110x3.5cm',45.00,15.00,'disponible',TO_DATE('2023-01-18','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-CEI-003','Ceinture Classique Premium','Ceintures','Ceinture classique','Noir','110x4cm',60.00,20.00,'disponible',TO_DATE('2023-02-08','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-CEI-004','Ceinture Classique Camel','Ceintures','Ceinture classique','Camel','110x3.5cm',65.00,22.00,'disponible',TO_DATE('2023-02-18','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-CEI-005','Ceinture Fashion Blanc','Ceintures','Ceinture fashion','Blanc','95x2.5cm',35.00,12.00,'disponible',TO_DATE('2023-03-08','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-CEI-006','Ceinture Fashion Rouge','Ceintures','Ceinture fashion','Rouge','95x2.5cm',38.00,13.00,'disponible',TO_DATE('2023-03-18','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-CEI-007','Ceinture Fashion Noir','Ceintures','Ceinture fashion','Noir','95x3cm',48.00,16.00,'disponible',TO_DATE('2023-04-08','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-CEI-008','Ceinture Luxe Noir','Ceintures','Ceinture luxe','Noir','110x4cm',110.00,35.00,'disponible',TO_DATE('2023-04-18','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-CEI-009','Ceinture Luxe Marron','Ceintures','Ceinture luxe','Marron','110x4cm',110.00,35.00,'disponible',TO_DATE('2023-05-08','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-CEI-010','Ceinture Homme Élégante','Ceintures','Ceinture classique','Noir','115x3.5cm',55.00,18.00,'disponible',TO_DATE('2023-05-18','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-CEI-011','Ceinture Femme Mode','Ceintures','Ceinture fashion','Beige','95x2.5cm',32.00,11.00,'disponible',TO_DATE('2023-06-08','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-CEI-012','Ceinture Réversible','Ceintures','Ceinture classique','Marron','110x3.5cm',52.00,17.00,'disponible',TO_DATE('2023-06-18','YYYY-MM-DD'));

-- ACCESSOIRES (13 articles)
INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-ACC-001','Porte-Monnaie Noir','Accessoires','Porte-monnaie','Noir','12x9x2cm',22.00,8.00,'disponible',TO_DATE('2023-01-12','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-ACC-002','Porte-Monnaie Rouge','Accessoires','Porte-monnaie','Rouge','12x9x2cm',22.00,8.00,'disponible',TO_DATE('2023-01-22','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-ACC-003','Porte-Monnaie Camel','Accessoires','Porte-monnaie','Camel','12x9x2cm',28.00,10.00,'disponible',TO_DATE('2023-02-12','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-ACC-004','Porte-Clés Noir','Accessoires','Porte-clés','Noir','10x5cm',15.00,5.00,'disponible',TO_DATE('2023-02-22','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-ACC-005','Porte-Clés Marron','Accessoires','Porte-clés','Marron','10x5cm',15.00,5.00,'disponible',TO_DATE('2023-03-12','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-ACC-006','Porte-Clés Premium','Accessoires','Porte-clés','Camel','10x5cm',20.00,7.00,'disponible',TO_DATE('2023-03-22','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-ACC-007','Pochette Noir','Accessoires','Pochette','Noir','22x15x3cm',50.00,18.00,'disponible',TO_DATE('2023-04-12','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-ACC-008','Pochette Marron','Accessoires','Pochette','Marron','22x15x3cm',55.00,20.00,'disponible',TO_DATE('2023-04-22','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-ACC-009','Pochette Camel','Accessoires','Pochette','Camel','22x15x3cm',62.00,22.00,'disponible',TO_DATE('2023-05-12','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-ACC-010','Bandoulière Noir','Accessoires','Bandoulière','Noir','120x2cm',32.00,12.00,'disponible',TO_DATE('2023-05-22','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-ACC-011','Bandoulière Marron','Accessoires','Bandoulière','Marron','120x2cm',38.00,14.00,'disponible',TO_DATE('2023-06-12','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-ACC-012','Porte-Monnaie Zip','Accessoires','Porte-monnaie','Rouge','12x9x2cm',20.00,8.00,'disponible',TO_DATE('2023-06-22','YYYY-MM-DD'));

INSERT INTO REF_ARTICLES_MARCHE (REFERENCE,NOM,CATEGORIE,TYPE,COULEUR,DIMENSION,PRIX_UNITAIRE,COUT_FABRICATION,STATUT,DATE_CREATION)
VALUES ('REF-ACC-013','Pochette Soirée','Accessoires','Pochette','Noir','20x12x3cm',58.00,20.00,'disponible',TO_DATE('2023-07-01','YYYY-MM-DD'));

COMMIT;

-- ================================================================
-- VÉRIFICATION
-- ================================================================
SELECT CATEGORIE,
       COUNT(*)                                    AS NB_ARTICLES,
       ROUND(AVG(PRIX_UNITAIRE), 2)                AS PRIX_MOY,
       ROUND(AVG(COUT_FABRICATION), 2)             AS COUT_MOY,
       ROUND(AVG(PRIX_UNITAIRE/COUT_FABRICATION),2) AS RATIO_MOY
FROM REF_ARTICLES_MARCHE
GROUP BY CATEGORIE
ORDER BY CATEGORIE;
