-- ============================================================
-- SCRIPT: Ajouter attributs pointage dans table EMPLOYES
-- ============================================================

-- 1. Ajouter les nouvelles colonnes (une par une pour eviter erreur si existe)

-- DATE_DERNIER_POINTAGE
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE CUIREA.EMPLOYES ADD DATE_DERNIER_POINTAGE DATE';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- HEURE_ARRIVEE
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE CUIREA.EMPLOYES ADD HEURE_ARRIVEE TIMESTAMP';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- HEURE_DEPART
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE CUIREA.EMPLOYES ADD HEURE_DEPART TIMESTAMP';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- STATUT_POINTAGE
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE CUIREA.EMPLOYES ADD STATUT_POINTAGE VARCHAR2(20) DEFAULT ''ABSENT''';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- 2. Verifier la structure
SELECT COLUMN_NAME, DATA_TYPE 
FROM ALL_TAB_COLUMNS 
WHERE TABLE_NAME = 'EMPLOYES' AND OWNER = 'CUIREA'
ORDER BY COLUMN_ID;

-- 3. Voir les employes avec leur UID
SELECT ID_EMPLOYE, NOM, PRENOM, UID_CARTE 
FROM CUIREA.EMPLOYES;
