-- Script de création de la table COMMANDES pour la gestion de production
-- Base de données Oracle

CREATE TABLE COMMANDES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REFERENCE VARCHAR2(50) NOT NULL UNIQUE,
    CLIENT VARCHAR2(200) NOT NULL,
    TYPE VARCHAR2(50) DEFAULT 'Standard',
    MONTANT_HT NUMBER(10,2) DEFAULT 0.00,
    DATE_CREATION DATE DEFAULT SYSDATE,
    DATE_LIVRAISON DATE NOT NULL,
    STATUT VARCHAR2(50) DEFAULT 'En attente',
    PRIORITE VARCHAR2(50) DEFAULT 'Normale',
    CONSTRAINT chk_montant CHECK (MONTANT_HT >= 0),
    CONSTRAINT chk_dates CHECK (DATE_LIVRAISON >= DATE_CREATION),
    CONSTRAINT chk_statut CHECK (STATUT IN ('En Attente', 'Planifié', 'En Production', 'Terminé')),
    CONSTRAINT chk_priorite CHECK (PRIORITE IN ('Basse', 'Normale', 'Haute', 'Urgente'))
);

-- Index pour améliorer les performances
CREATE INDEX idx_commandes_reference ON COMMANDES(REFERENCE);
CREATE INDEX idx_commandes_client ON COMMANDES(CLIENT);
CREATE INDEX idx_commandes_statut ON COMMANDES(STATUT);
CREATE INDEX idx_commandes_date_creation ON COMMANDES(DATE_CREATION);
CREATE INDEX idx_commandes_date_livraison ON COMMANDES(DATE_LIVRAISON);

-- Données de test
INSERT INTO COMMANDES (REFERENCE, CLIENT, TYPE, MONTANT_HT, DATE_CREATION, DATE_LIVRAISON, STATUT, PRIORITE)
VALUES ('PROD-2024-001', 'Leather Masters SA', 'Sacs en Cuir', 15500.00, TO_DATE('2024-01-15', 'YYYY-MM-DD'), TO_DATE('2024-02-15', 'YYYY-MM-DD'), 'En Production', 'Haute');

INSERT INTO COMMANDES (REFERENCE, CLIENT, TYPE, MONTANT_HT, DATE_CREATION, DATE_LIVRAISON, STATUT, PRIORITE)
VALUES ('PROD-2024-002', 'Textile Excellence', 'Vêtements', 8200.00, TO_DATE('2024-01-18', 'YYYY-MM-DD'), TO_DATE('2024-02-20', 'YYYY-MM-DD'), 'Planifié', 'Normale');

INSERT INTO COMMANDES (REFERENCE, CLIENT, TYPE, MONTANT_HT, DATE_CREATION, DATE_LIVRAISON, STATUT, PRIORITE)
VALUES ('PROD-2024-003', 'Fashion Accessories Ltd', 'Accessoires', 3750.00, TO_DATE('2024-01-20', 'YYYY-MM-DD'), TO_DATE('2024-02-10', 'YYYY-MM-DD'), 'En Production', 'Haute');

INSERT INTO COMMANDES (REFERENCE, CLIENT, TYPE, MONTANT_HT, DATE_CREATION, DATE_LIVRAISON, STATUT, PRIORITE)
VALUES ('PROD-2024-004', 'Premium Bags Co', 'Sacs Premium', 22000.00, TO_DATE('2024-01-22', 'YYYY-MM-DD'), TO_DATE('2024-03-01', 'YYYY-MM-DD'), 'En Attente', 'Basse');

INSERT INTO COMMANDES (REFERENCE, CLIENT, TYPE, MONTANT_HT, DATE_CREATION, DATE_LIVRAISON, STATUT, PRIORITE)
VALUES ('PROD-2024-005', 'Style Clothing', 'Collection Été', 12800.00, TO_DATE('2024-01-25', 'YYYY-MM-DD'), TO_DATE('2024-02-28', 'YYYY-MM-DD'), 'En Production', 'Normale');

INSERT INTO COMMANDES (REFERENCE, CLIENT, TYPE, MONTANT_HT, DATE_CREATION, DATE_LIVRAISON, STATUT, PRIORITE)
VALUES ('PROD-2024-006', 'Quality Leather Supply', 'Cuir Traité', 9500.00, TO_DATE('2024-01-28', 'YYYY-MM-DD'), TO_DATE('2024-02-25', 'YYYY-MM-DD'), 'Terminé', 'Normale');

INSERT INTO COMMANDES (REFERENCE, CLIENT, TYPE, MONTANT_HT, DATE_CREATION, DATE_LIVRAISON, STATUT, PRIORITE)
VALUES ('PROD-2024-007', 'Modern Textiles', 'Tissus Techniques', 6300.00, TO_DATE('2024-02-01', 'YYYY-MM-DD'), TO_DATE('2024-03-05', 'YYYY-MM-DD'), 'Planifié', 'Basse');

INSERT INTO COMMANDES (REFERENCE, CLIENT, TYPE, MONTANT_HT, DATE_CREATION, DATE_LIVRAISON, STATUT, PRIORITE)
VALUES ('PROD-2024-008', 'Elite Accessories', 'Bijoux Mode', 4200.00, TO_DATE('2024-02-03', 'YYYY-MM-DD'), TO_DATE('2024-02-18', 'YYYY-MM-DD'), 'En Production', 'Haute');

INSERT INTO COMMANDES (REFERENCE, CLIENT, TYPE, MONTANT_HT, DATE_CREATION, DATE_LIVRAISON, STATUT, PRIORITE)
VALUES ('PROD-2024-009', 'Luxury Bags Import', 'Sacs Luxe', 28500.00, TO_DATE('2024-02-05', 'YYYY-MM-DD'), TO_DATE('2024-03-15', 'YYYY-MM-DD'), 'En Attente', 'Haute');

INSERT INTO COMMANDES (REFERENCE, CLIENT, TYPE, MONTANT_HT, DATE_CREATION, DATE_LIVRAISON, STATUT, PRIORITE)
VALUES ('PROD-2024-010', 'Fashion Forward', 'Prêt-à-Porter', 11200.00, TO_DATE('2024-02-07', 'YYYY-MM-DD'), TO_DATE('2024-03-10', 'YYYY-MM-DD'), 'Planifié', 'Normale');

COMMIT;
