-- VERSION ULTRA-SIMPLIFIÉE - Copier-coller ligne par ligne dans SQL Developer

-- 1. Supprimer la table si elle existe
DROP TABLE COMMANDES CASCADE CONSTRAINTS;

-- 2. Créer la table (SANS contraintes compliquées)
CREATE TABLE COMMANDES (
    ID_COMMANDE NUMBER PRIMARY KEY,
    REFERENCE VARCHAR2(50) NOT NULL UNIQUE,
    TYPE VARCHAR2(50),
    MONTANT NUMBER(12,2),
    DATE_CREATION DATE,
    DATE_LIVRAISON DATE,
    STATUT VARCHAR2(50),
    PRIORITE VARCHAR2(50),
    ETAT VARCHAR2(50),
    ID_CLIENT NUMBER,
    ID_EMPLOYE NUMBER
);

-- 3. Créer la séquence pour l'auto-increment
CREATE SEQUENCE SEQ_COMMANDES START WITH 1 INCREMENT BY 1;

-- 4. Créer le trigger pour l'auto-increment
CREATE OR REPLACE TRIGGER TRG_COMMANDES_ID
BEFORE INSERT ON COMMANDES
FOR EACH ROW
BEGIN
  IF :NEW.ID_COMMANDE IS NULL THEN
    SELECT SEQ_COMMANDES.NEXTVAL INTO :NEW.ID_COMMANDE FROM DUAL;
  END IF;
END;
/

-- 5. Insérer UNE donnée de test
INSERT INTO COMMANDES (REFERENCE, TYPE, MONTANT, DATE_CREATION, DATE_LIVRAISON, STATUT, PRIORITE)
VALUES ('TEST-001', 'Test', 100, SYSDATE, SYSDATE+30, 'En Attente', 'Normale');

-- 6. Vérifier
SELECT * FROM COMMANDES;

COMMIT;
