-- Script de création de la table COMMANDES pour l'utilisateur CUIREA
-- À exécuter dans SQL Developer connecté en tant que CUIREA

-- Supprimer la table si elle existe déjà
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE COMMANDES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- Créer la séquence pour l'ID
CREATE SEQUENCE SEQ_COMMANDES_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Créer la table COMMANDES
CREATE TABLE COMMANDES (
    ID_COMMANDE NUMBER DEFAULT SEQ_COMMANDES_ID.NEXTVAL PRIMARY KEY,
    REFERENCE VARCHAR2(50) NOT NULL UNIQUE,
    TYPE VARCHAR2(50) DEFAULT 'Standard',
    MONTANT NUMBER(12,2) DEFAULT 0.00,
    DATE_CREATION DATE DEFAULT SYSDATE,
    DATE_LIVRAISON DATE NOT NULL,
    STATUT VARCHAR2(50) DEFAULT 'En Attente',
    PRIORITE VARCHAR2(50) DEFAULT 'Normale',
    ETAT VARCHAR2(50),
    ID_CLIENT NUMBER,
    ID_EMPLOYE NUMBER
);

-- Créer les index
CREATE INDEX idx_commandes_reference ON COMMANDES(REFERENCE);
CREATE INDEX idx_commandes_statut ON COMMANDES(STATUT);
CREATE INDEX idx_commandes_date_creation ON COMMANDES(DATE_CREATION);
CREATE INDEX idx_commandes_date_livraison ON COMMANDES(DATE_LIVRAISON);

-- Insérer des données de test
INSERT INTO COMMANDES (REFERENCE, TYPE, MONTANT, DATE_CREATION, DATE_LIVRAISON, STATUT, PRIORITE)
VALUES ('PROD-2024-001', 'Sacs en Cuir', 15500.00, TO_DATE('2024-01-15', 'YYYY-MM-DD'), TO_DATE('2024-02-15', 'YYYY-MM-DD'), 'En Production', 'Haute');

INSERT INTO COMMANDES (REFERENCE, TYPE, MONTANT, DATE_CREATION, DATE_LIVRAISON, STATUT, PRIORITE)
VALUES ('PROD-2024-002', 'Vêtements', 8200.00, TO_DATE('2024-01-18', 'YYYY-MM-DD'), TO_DATE('2024-02-20', 'YYYY-MM-DD'), 'Planifié', 'Normale');

INSERT INTO COMMANDES (REFERENCE, TYPE, MONTANT, DATE_CREATION, DATE_LIVRAISON, STATUT, PRIORITE)
VALUES ('PROD-2024-003', 'Accessoires', 3750.00, TO_DATE('2024-01-20', 'YYYY-MM-DD'), TO_DATE('2024-02-10', 'YYYY-MM-DD'), 'En Production', 'Haute');

INSERT INTO COMMANDES (REFERENCE, TYPE, MONTANT, DATE_CREATION, DATE_LIVRAISON, STATUT, PRIORITE)
VALUES ('PROD-2024-004', 'Sacs Premium', 22000.00, TO_DATE('2024-01-22', 'YYYY-MM-DD'), TO_DATE('2024-03-01', 'YYYY-MM-DD'), 'En Attente', 'Basse');

INSERT INTO COMMANDES (REFERENCE, TYPE, MONTANT, DATE_CREATION, DATE_LIVRAISON, STATUT, PRIORITE)
VALUES ('PROD-2024-005', 'Collection Été', 12800.00, TO_DATE('2024-01-25', 'YYYY-MM-DD'), TO_DATE('2024-02-28', 'YYYY-MM-DD'), 'En Production', 'Normale');

COMMIT;

-- Vérification
SELECT 'Table COMMANDES créée avec succès!' AS MESSAGE FROM DUAL;
SELECT COUNT(*) AS "Nombre de lignes" FROM COMMANDES;
SELECT * FROM COMMANDES ORDER BY ID_COMMANDE;
