-- Script de création de la table FOURNISSEUR pour Oracle
-- À exécuter dans SQL Developer ou SQL*Plus

-- Supprimer la table si elle existe déjà
DROP TABLE FOURNISSEUR CASCADE CONSTRAINTS;

-- Créer la séquence pour l'auto-incrémentation de l'ID
DROP SEQUENCE FOURNISSEUR_SEQ;
CREATE SEQUENCE FOURNISSEUR_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Créer la table FOURNISSEUR
CREATE TABLE FOURNISSEUR (
    ID NUMBER(10) PRIMARY KEY,
    NOM_ENTREPRISE VARCHAR2(200) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    TELEPHONE VARCHAR2(20) NOT NULL,
    MATRICULE_FISCAL VARCHAR2(50) NOT NULL UNIQUE,
    TYPE_PRODUIT VARCHAR2(100) NOT NULL,
    CONDITION_PAIEMENT VARCHAR2(100) NOT NULL,
    STATUT VARCHAR2(20) DEFAULT 'ACTIF' NOT NULL,
    DATE_CREATION DATE DEFAULT SYSDATE,
    CONSTRAINT CHK_STATUT CHECK (STATUT IN ('Actif', 'Suspendu', 'Inactif'))
);

-- Créer un trigger pour l'auto-incrémentation de l'ID
CREATE OR REPLACE TRIGGER FOURNISSEUR_TRG
BEFORE INSERT ON FOURNISSEUR
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT FOURNISSEUR_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Insérer des données de test
INSERT INTO FOURNISSEUR (NOM_ENTREPRISE, EMAIL, TELEPHONE, MATRICULE_FISCAL, TYPE_PRODUIT, CONDITION_PAIEMENT, STATUT)
VALUES ('Leather Premium Co.', 'contact@leatherpremium.com', '0612345678', 'MF/A/123456', 'Cuir', 'Virement', 'Actif');

INSERT INTO FOURNISSEUR (NOM_ENTREPRISE, EMAIL, TELEPHONE, MATRICULE_FISCAL, TYPE_PRODUIT, CONDITION_PAIEMENT, STATUT)
VALUES ('Textile Supplies Ltd', 'info@textilesupplies.com', '0623456789', 'MF/B/234567', 'Tissus', 'Carte Bancaire', 'Actif');

INSERT INTO FOURNISSEUR (NOM_ENTREPRISE, EMAIL, TELEPHONE, MATRICULE_FISCAL, TYPE_PRODUIT, CONDITION_PAIEMENT, STATUT)
VALUES ('Metal Accessories Inc', 'sales@metalacc.com', '0634567890', 'MF/C/345678', 'Accessoires', 'Virement', 'Actif');

INSERT INTO FOURNISSEUR (NOM_ENTREPRISE, EMAIL, TELEPHONE, MATRICULE_FISCAL, TYPE_PRODUIT, CONDITION_PAIEMENT, STATUT)
VALUES ('Zipper World', 'contact@zipperworld.com', '0645678901', 'MF/D/456789', 'Accessoires', 'Carte Bancaire', 'Actif');

INSERT INTO FOURNISSEUR (NOM_ENTREPRISE, EMAIL, TELEPHONE, MATRICULE_FISCAL, TYPE_PRODUIT, CONDITION_PAIEMENT, STATUT)
VALUES ('Button Factory', 'info@buttonfactory.com', '0656789012', 'MF/E/567890', 'Accessoires', 'Virement', 'Suspendu');

COMMIT;

-- Vérifier les données insérées
SELECT * FROM FOURNISSEUR ORDER BY ID;
