#include "mainwindow.h"
#include "ui_mainwindow.h"
#include "employeedialog.h"
#include "clientmanagerdialog.h"
#include <QTableWidgetItem>
#include <QDebug>
#include <QMessageBox>

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);
    
    setWindowTitle("CUIREA - Management System");
    
    // Hide vertical headers (row numbers)
    ui->employeeTable->verticalHeader()->setVisible(false);
    ui->clientTable->verticalHeader()->setVisible(false);
    
    // Populate employee table with sample data
    populateEmployeeTable();
    
    // Set column widths for employee table
    ui->employeeTable->setColumnWidth(0, 50);   // ID
    ui->employeeTable->setColumnWidth(1, 110);  // Matricule
    ui->employeeTable->setColumnWidth(2, 100);  // Nom
    ui->employeeTable->setColumnWidth(3, 100);  // Prenom
    ui->employeeTable->setColumnWidth(4, 100);  // CIN
    ui->employeeTable->setColumnWidth(5, 120);  // Date Naissance
    ui->employeeTable->setColumnWidth(6, 130);  // Departement
    ui->employeeTable->setColumnWidth(7, 120);  // Poste
    ui->employeeTable->setColumnWidth(8, 110);  // Telephone
    ui->employeeTable->setColumnWidth(9, 180);  // Email
    
    // Add sample clients
    Client c1;
    c1.setNom("Alami");
    c1.setPrenom("Hassan");
    c1.setSexe("Homme");
    c1.setCin("AB123456");
    c1.setPays("Maroc");
    c1.setVille("Casablanca");
    c1.setAdresse("123 Rue Mohammed V");
    c1.setEmail("h.alami@email.com");
    c1.setDateInscrit(QDate::currentDate().addDays(-30));
    clients.append(c1);
    
    Client c2;
    c2.setNom("Benali");
    c2.setPrenom("Fatima");
    c2.setSexe("Femme");
    c2.setCin("CD789012");
    c2.setPays("Maroc");
    c2.setVille("Rabat");
    c2.setAdresse("456 Avenue Hassan II");
    c2.setEmail("f.benali@email.com");
    c2.setDateInscrit(QDate::currentDate().addDays(-15));
    clients.append(c2);
    
    // Populate client table
    refreshClientTable();
    
    // Start with employee module (page 0)
    ui->stackedWidget->setCurrentIndex(0);
    ui->profilePanel->setVisible(true);
    
    // Set initial active button style
    ui->btnEmployees->setStyleSheet(
        "QPushButton { background-color: #6E473B; color: #FFFFFF; border-left: 3px solid #FFFFFF; }"
    );
    
    // Connect table selection to profile panel update
    connect(ui->employeeTable, &QTableWidget::currentCellChanged, this, &MainWindow::onEmployeeSelected);
}

MainWindow::~MainWindow()
{
    delete ui;
}

void MainWindow::refreshClientTable()
{
    ui->clientTable->setRowCount(clients.size());
    
    for (int i = 0; i < clients.size(); ++i) {
        const Client &c = clients[i];
        ui->clientTable->setItem(i, 0, new QTableWidgetItem(c.getNom()));
        ui->clientTable->setItem(i, 1, new QTableWidgetItem(c.getPrenom()));
        ui->clientTable->setItem(i, 2, new QTableWidgetItem(c.getSexe()));
        ui->clientTable->setItem(i, 3, new QTableWidgetItem(c.getCin()));
        ui->clientTable->setItem(i, 4, new QTableWidgetItem(c.getPays()));
        ui->clientTable->setItem(i, 5, new QTableWidgetItem(c.getVille()));
        ui->clientTable->setItem(i, 6, new QTableWidgetItem(c.getAdresse()));
        ui->clientTable->setItem(i, 7, new QTableWidgetItem(c.getEmail()));
    }
}

// ============================================
// NAVIGATION SLOTS (Auto-generated by Qt)
// ============================================

void MainWindow::on_btnEmployees_clicked()
{
    ui->stackedWidget->setCurrentIndex(0);  // Show employee page
    ui->profilePanel->setVisible(true);     // Show profile panel
    setWindowTitle("CUIREA - Gestion des Employés");
    
    // Reset all navigation buttons to default style
    ui->btnEmployees->setStyleSheet("");
    ui->btnClients->setStyleSheet("");
    ui->btnProducts->setStyleSheet("");
    ui->btnOrders->setStyleSheet("");
    ui->btnRawMaterials->setStyleSheet("");
    ui->btnSuppliers->setStyleSheet("");
    
    // Apply active style to current button
    ui->btnEmployees->setStyleSheet(
        "QPushButton { background-color: #6E473B; color: #FFFFFF; border-left: 3px solid #FFFFFF; }"
    );
}

void MainWindow::on_btnClients_clicked()
{
    ui->stackedWidget->setCurrentIndex(1);  // Show client page
    ui->profilePanel->setVisible(false);    // Hide profile panel
    setWindowTitle("CUIREA - Gestion des Clients");
    
    // Reset all navigation buttons to default style
    ui->btnEmployees->setStyleSheet("");
    ui->btnClients->setStyleSheet("");
    ui->btnProducts->setStyleSheet("");
    ui->btnOrders->setStyleSheet("");
    ui->btnRawMaterials->setStyleSheet("");
    ui->btnSuppliers->setStyleSheet("");
    
    // Apply active style to current button
    ui->btnClients->setStyleSheet(
        "QPushButton { background-color: #6E473B; color: #FFFFFF; border-left: 3px solid #FFFFFF; }"
    );
}

void MainWindow::on_btnProducts_clicked()
{
    QMessageBox msgBox(this);
    msgBox.setWindowTitle("Module en développement");
    msgBox.setText("Gestion des Produits");
    msgBox.setInformativeText("Ce module sera disponible prochainement.\n\n"
                              "Fonctionnalités prévues :\n"
                              "• Ajout et modification\n"
                              "• Recherche et filtrage\n"
                              "• Export des données\n"
                              "• Rapports et statistiques");
    msgBox.setIcon(QMessageBox::Information);
    msgBox.setStyleSheet(
        "QMessageBox { background-color: #FAF5F0; }"
        "QMessageBox QLabel { color: #291C0E; font-family: Arial, sans-serif; font-size: 12px; }"
        "QPushButton { background-color: #8D6E63; color: white; border: none; border-radius: 6px; "
        "padding: 8px 20px; font-family: Arial, sans-serif; font-size: 11px; font-weight: bold; min-width: 80px; }"
        "QPushButton:hover { background-color: #A0826D; }"
    );
    msgBox.exec();
}

void MainWindow::on_btnOrders_clicked()
{
    QMessageBox msgBox(this);
    msgBox.setWindowTitle("Module en développement");
    msgBox.setText("Gestion des Commandes");
    msgBox.setInformativeText("Ce module sera disponible prochainement.\n\n"
                              "Fonctionnalités prévues :\n"
                              "• Ajout et modification\n"
                              "• Recherche et filtrage\n"
                              "• Export des données\n"
                              "• Rapports et statistiques");
    msgBox.setIcon(QMessageBox::Information);
    msgBox.setStyleSheet(
        "QMessageBox { background-color: #FAF5F0; }"
        "QMessageBox QLabel { color: #291C0E; font-family: Arial, sans-serif; font-size: 12px; }"
        "QPushButton { background-color: #8D6E63; color: white; border: none; border-radius: 6px; "
        "padding: 8px 20px; font-family: Arial, sans-serif; font-size: 11px; font-weight: bold; min-width: 80px; }"
        "QPushButton:hover { background-color: #A0826D; }"
    );
    msgBox.exec();
}

void MainWindow::on_btnRawMaterials_clicked()
{
    QMessageBox msgBox(this);
    msgBox.setWindowTitle("Module en développement");
    msgBox.setText("Gestion des Matières Premières");
    msgBox.setInformativeText("Ce module sera disponible prochainement.\n\n"
                              "Fonctionnalités prévues :\n"
                              "• Ajout et modification\n"
                              "• Recherche et filtrage\n"
                              "• Export des données\n"
                              "• Rapports et statistiques");
    msgBox.setIcon(QMessageBox::Information);
    msgBox.setStyleSheet(
        "QMessageBox { background-color: #FAF5F0; }"
        "QMessageBox QLabel { color: #291C0E; font-family: Arial, sans-serif; font-size: 12px; }"
        "QPushButton { background-color: #8D6E63; color: white; border: none; border-radius: 6px; "
        "padding: 8px 20px; font-family: Arial, sans-serif; font-size: 11px; font-weight: bold; min-width: 80px; }"
        "QPushButton:hover { background-color: #A0826D; }"
    );
    msgBox.exec();
}

void MainWindow::on_btnSuppliers_clicked()
{
    QMessageBox msgBox(this);
    msgBox.setWindowTitle("Module en développement");
    msgBox.setText("Gestion des Fournisseurs");
    msgBox.setInformativeText("Ce module sera disponible prochainement.\n\n"
                              "Fonctionnalités prévues :\n"
                              "• Ajout et modification\n"
                              "• Recherche et filtrage\n"
                              "• Export des données\n"
                              "• Rapports et statistiques");
    msgBox.setIcon(QMessageBox::Information);
    msgBox.setStyleSheet(
        "QMessageBox { background-color: #FAF5F0; }"
        "QMessageBox QLabel { color: #291C0E; font-family: Arial, sans-serif; font-size: 12px; }"
        "QPushButton { background-color: #8D6E63; color: white; border: none; border-radius: 6px; "
        "padding: 8px 20px; font-family: Arial, sans-serif; font-size: 11px; font-weight: bold; min-width: 80px; }"
        "QPushButton:hover { background-color: #A0826D; }"
    );
    msgBox.exec();
}

// ============================================
// EMPLOYEE CRUD SLOTS (Auto-generated by Qt)
// ============================================

void MainWindow::on_btnAdd_clicked()
{
    EmployeeDialog dialog(this, EmployeeDialog::AddMode);
    dialog.exec();
}

void MainWindow::on_btnEdit_clicked()
{
    int currentRow = ui->employeeTable->currentRow();
    if (currentRow < 0) {
        QMessageBox::warning(this, "Aucune sélection",
                           "Veuillez sélectionner un employé à modifier.");
        return;
    }
    
    EmployeeDialog dialog(this, EmployeeDialog::EditMode);
    
    // Get employee data from table
    QString id = ui->employeeTable->item(currentRow, 0)->text();
    QString matricule = ui->employeeTable->item(currentRow, 1)->text();
    QString nom = ui->employeeTable->item(currentRow, 2)->text();
    QString prenom = ui->employeeTable->item(currentRow, 3)->text();
    QString cin = ui->employeeTable->item(currentRow, 4)->text();
    QString dateNaissance = ui->employeeTable->item(currentRow, 5)->text();
    QString departement = ui->employeeTable->item(currentRow, 6)->text();
    QString poste = ui->employeeTable->item(currentRow, 7)->text();
    QString telephone = ui->employeeTable->item(currentRow, 8)->text();
    QString email = ui->employeeTable->item(currentRow, 9)->text();
    
    dialog.setEmployeeData(id, matricule, nom, prenom, cin, dateNaissance,
                          "Homme", "", telephone, email, poste, "", departement, "01/01/2024");
    dialog.exec();
}

void MainWindow::on_btnDelete_clicked()
{
    int currentRow = ui->employeeTable->currentRow();
    if (currentRow < 0) {
        QMessageBox::warning(this, "Aucune sélection",
                           "Veuillez sélectionner un employé à supprimer.");
        return;
    }
    
    // Get employee data
    QString id = ui->employeeTable->item(currentRow, 0)->text();
    QString matricule = ui->employeeTable->item(currentRow, 1)->text();
    QString nom = ui->employeeTable->item(currentRow, 2)->text();
    QString prenom = ui->employeeTable->item(currentRow, 3)->text();
    QString departement = ui->employeeTable->item(currentRow, 6)->text();
    QString poste = ui->employeeTable->item(currentRow, 7)->text();
    
    EmployeeDialog dialog(this, EmployeeDialog::DeleteMode);
    dialog.setEmployeeData(id, matricule, nom, prenom, "", "", "", "", "", "", poste, "", departement, "");
    dialog.exec();
}

void MainWindow::on_btnExport_clicked()
{
    EmployeeDialog dialog(this, EmployeeDialog::ExportMode);
    dialog.exec();
}

// ============================================
// CLIENT CRUD SLOTS (Auto-generated by Qt)
// ============================================

void MainWindow::on_btnAddClient_clicked()
{
    ClientManagerDialog dlg(this, ClientManagerDialog::AddMode);
    dlg.exec();
}

void MainWindow::on_btnEditClient_clicked()
{
    int currentRow = ui->clientTable->currentRow();
    if (currentRow < 0) {
        QMessageBox::warning(this, "Aucune sélection",
                           "Veuillez sélectionner un client à modifier.");
        return;
    }
    
    // Get current client data
    QString nom = ui->clientTable->item(currentRow, 0)->text();
    QString prenom = ui->clientTable->item(currentRow, 1)->text();
    QString sexe = ui->clientTable->item(currentRow, 2)->text();
    QString cin = ui->clientTable->item(currentRow, 3)->text();
    QString pays = ui->clientTable->item(currentRow, 4)->text();
    QString ville = ui->clientTable->item(currentRow, 5)->text();
    QString adresse = ui->clientTable->item(currentRow, 6)->text();
    QString email = ui->clientTable->item(currentRow, 7)->text();
    
    // Open edit dialog
    ClientManagerDialog dlg(this, ClientManagerDialog::EditMode);
    dlg.setClientData(nom, prenom, sexe, cin, pays, ville, adresse, email);
    dlg.exec();
}

void MainWindow::on_btnDeleteClient_clicked()
{
    int currentRow = ui->clientTable->currentRow();
    if (currentRow < 0) {
        QMessageBox::warning(this, "Aucune sélection",
                           "Veuillez sélectionner un client à supprimer.");
        return;
    }
    
    // Get client data
    QString nom = ui->clientTable->item(currentRow, 0)->text();
    QString prenom = ui->clientTable->item(currentRow, 1)->text();
    QString sexe = ui->clientTable->item(currentRow, 2)->text();
    QString cin = ui->clientTable->item(currentRow, 3)->text();
    QString pays = ui->clientTable->item(currentRow, 4)->text();
    QString ville = ui->clientTable->item(currentRow, 5)->text();
    
    ClientManagerDialog dlg(this, ClientManagerDialog::DeleteMode);
    dlg.setClientData(nom, prenom, sexe, cin, pays, ville, "", "");
    dlg.exec();
}

void MainWindow::on_btnExportClient_clicked()
{
    ClientManagerDialog dialog(this, ClientManagerDialog::ExportMode);
    dialog.exec();
}

void MainWindow::on_btnRefreshClient_clicked()
{
    QMessageBox msgBox(this);
    msgBox.setWindowTitle("Actualisation");
    msgBox.setText("Liste des clients actualisée !");
    msgBox.setInformativeText("(Mode statique - données d'exemple)");
    msgBox.setIcon(QMessageBox::Information);
    msgBox.setStyleSheet(
        "QMessageBox { background-color: #FAF5F0; }"
        "QMessageBox QLabel { color: #291C0E; font-family: Arial, sans-serif; font-size: 12px; }"
        "QPushButton { background-color: #8D6E63; color: white; border: none; border-radius: 6px; "
        "padding: 8px 20px; font-family: Arial, sans-serif; font-size: 11px; font-weight: bold; min-width: 80px; }"
        "QPushButton:hover { background-color: #A0826D; }"
    );
    msgBox.exec();
}

void MainWindow::populateEmployeeTable()
{
    qDebug() << "populateEmployeeTable called";
    
    ui->employeeTable->setRowCount(15);
    
    struct Employee {
        QString id;
        QString matricule;
        QString nom;
        QString prenom;
        QString cin;
        QString dateNaissance;
        QString departement;
        QString poste;
        QString telephone;
        QString email;
    };
    
    Employee employees[] = {
        {"001", "EMP-2024-001", "Benali", "Ahmed", "AB123456", "15/03/1985", "Production", "Supervisor", "0612345678", "a.benali@cuirea.com"},
        {"002", "EMP-2024-002", "Zahra", "Fatima", "CD234567", "22/07/1990", "Quality Control", "Inspector", "0623456789", "f.zahra@cuirea.com"},
        {"003", "EMP-2024-003", "Alami", "Mohammed", "EF345678", "10/11/1988", "Cutting", "Operator", "0634567890", "m.alami@cuirea.com"},
        {"004", "EMP-2024-004", "Mansouri", "Khadija", "GH456789", "05/02/1992", "Stitching", "Team Leader", "0645678901", "k.mansouri@cuirea.com"},
        {"005", "EMP-2024-005", "Idrissi", "Youssef", "IJ567890", "18/09/1987", "Finishing", "Technician", "0656789012", "y.idrissi@cuirea.com"},
        {"006", "EMP-2024-006", "Tazi", "Amina", "KL678901", "30/04/1991", "Design", "Designer", "0667890123", "a.tazi@cuirea.com"},
        {"007", "EMP-2024-007", "Berrada", "Hassan", "MN789012", "12/06/1983", "Warehouse", "Manager", "0678901234", "h.berrada@cuirea.com"},
        {"008", "EMP-2024-008", "Chraibi", "Salma", "OP890123", "25/12/1989", "Administration", "HR Officer", "0689012345", "s.chraibi@cuirea.com"},
        {"009", "EMP-2024-009", "Fassi", "Rachid", "QR901234", "08/08/1986", "Maintenance", "Technician", "0690123456", "r.fassi@cuirea.com"},
        {"010", "EMP-2024-010", "Lahlou", "Nadia", "ST012345", "14/01/1993", "Packaging", "Operator", "0601234567", "n.lahlou@cuirea.com"},
        {"011", "EMP-2024-011", "Benjelloun", "Karim", "UV123456", "20/05/1984", "Production", "Operator", "0612345679", "k.benjelloun@cuirea.com"},
        {"012", "EMP-2024-012", "Ouazzani", "Leila", "WX234567", "03/10/1991", "Quality Control", "Analyst", "0623456780", "l.ouazzani@cuirea.com"},
        {"013", "EMP-2024-013", "Kettani", "Omar", "YZ345678", "17/03/1988", "Cutting", "Supervisor", "0634567891", "o.kettani@cuirea.com"},
        {"014", "EMP-2024-014", "Filali", "Samira", "AB456789", "28/11/1990", "Stitching", "Operator", "0645678902", "s.filali@cuirea.com"},
        {"015", "EMP-2024-015", "Tounsi", "Mehdi", "CD567890", "09/07/1989", "Finishing", "Operator", "0656789013", "m.tounsi@cuirea.com"}
    };
    
    for (int i = 0; i < 15; ++i) {
        ui->employeeTable->setItem(i, 0, new QTableWidgetItem(employees[i].id));
        ui->employeeTable->setItem(i, 1, new QTableWidgetItem(employees[i].matricule));
        ui->employeeTable->setItem(i, 2, new QTableWidgetItem(employees[i].nom));
        ui->employeeTable->setItem(i, 3, new QTableWidgetItem(employees[i].prenom));
        ui->employeeTable->setItem(i, 4, new QTableWidgetItem(employees[i].cin));
        ui->employeeTable->setItem(i, 5, new QTableWidgetItem(employees[i].dateNaissance));
        ui->employeeTable->setItem(i, 6, new QTableWidgetItem(employees[i].departement));
        ui->employeeTable->setItem(i, 7, new QTableWidgetItem(employees[i].poste));
        ui->employeeTable->setItem(i, 8, new QTableWidgetItem(employees[i].telephone));
        ui->employeeTable->setItem(i, 9, new QTableWidgetItem(employees[i].email));
    }
    
    qDebug() << "Table populated with" << ui->employeeTable->rowCount() << "rows";
}

void MainWindow::onEmployeeSelected()
{
    int currentRow = ui->employeeTable->currentRow();
    if (currentRow < 0) {
        return;
    }
    
    QString matricule = ui->employeeTable->item(currentRow, 1)->text();
    QString nom = ui->employeeTable->item(currentRow, 2)->text();
    QString prenom = ui->employeeTable->item(currentRow, 3)->text();
    QString cin = ui->employeeTable->item(currentRow, 4)->text();
    QString dateNaissance = ui->employeeTable->item(currentRow, 5)->text();
    QString departement = ui->employeeTable->item(currentRow, 6)->text();
    QString poste = ui->employeeTable->item(currentRow, 7)->text();
    QString telephone = ui->employeeTable->item(currentRow, 8)->text();
    QString email = ui->employeeTable->item(currentRow, 9)->text();
    
    ui->profileValue->setText(matricule);
    ui->profileValue_2->setText(nom);
    ui->profileValue_3->setText(prenom);
    ui->profileValue_4->setText(cin);
    ui->profileValue_5->setText(dateNaissance);
    ui->profileValue_6->setText("M");
    ui->profileValue_7->setText("Casablanca");
    ui->profileValue_8->setText(telephone);
    ui->profileValue_9->setText(email);
    ui->profileValue_10->setText(poste);
    ui->profileValue_11->setText(departement);
    ui->profileValue_12->setText(departement);
    ui->profileValue_13->setText("01/01/2024");
    
    ui->photoPlaceholder->clear();
    ui->photoPlaceholder->setText("●");
}
